import axios from 'axios'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import useSWR from 'swr'
import { useState } from 'react'

export default function Home() {
  const [search, setSearch] = useState('');
  const fetcher = url => axios.get(url).then(res => res.data)
  const { data, error } = useSWR('https://api.publicapis.org/categories', fetcher)
  console.log(data);
  
  if (error) return <div>error</div>
  if (!data) return <div>loading...</div>
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <input value={search} onChange={(v)=>setSearch(v.target.value)}/>
        <ul>
        {data.categories?.filter((v)=>v.toUpperCase().includes(search.toUpperCase())).map((value,index)=>(
            <li key={index}>
              {value}
            </li>
        ))}
        </ul>
      </main>
    </div>
  )
}
